# Generated by Django 3.2.25 on 2024-12-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing', '0007_auto_20241228_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentalwellbeingcontent',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
