# Generated by Django 3.2.25 on 2025-01-03 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wellbeing', '0008_mentalwellbeingcontent_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Mood Magic', 'Mood Magic'), ('Vibe Guide', 'Vibe Guide'), ('Wellness Wingman', 'Wellness Wingman'), ('general', 'General Feedback')], max_length=50)),
                ('rating', models.IntegerField(default=1)),
                ('comments', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
