# Generated by Django 3.2.25 on 2025-01-03 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wellbeing', '0009_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('vip', 'VIP')], max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('duration_minutes', models.PositiveIntegerField(default=20)),
                ('features', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wellbeing.membershipplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipUpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_on', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('processed_on', models.DateTimeField(blank=True, null=True)),
                ('requested_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_requests', to='wellbeing.membershipplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
